using System;
using System.Collections.Generic;
using Reflex.Core;
using UnityEngine;
using Unidad.Core.Bootstrap;
using Unidad.Core.EventBus;
using Unidad.Core.Factory;
using Unidad.Core.Testing;

namespace Unidad.Core.ModelCatalog
{
    /// <summary>
    /// Installer base for the model catalog system (picoCAD → Unity pipeline runtime).
    /// Abstract on purpose: each game declares a sealed subclass and overrides the
    /// hooks to register its per-kind effect profiles and view factories — that
    /// per-kind code is project content (generated by the /picocad-model pipeline
    /// into the game assembly), while the catalog machinery lives in the package.
    /// </summary>
    public abstract class ModelCatalogInstallerBase : ISystemInstaller
    {
        /// <summary>
        /// Effect profiles to register on the production resolver. The default
        /// "bounce" profile is always included; override to add per-kind profiles
        /// (iterate the base implementation to keep "bounce").
        /// </summary>
        protected virtual IEnumerable<Effects.IModelEffectProfile> CreateEffectProfiles()
        {
            yield return new Effects.BounceEffectProfile();
        }

        /// <summary>
        /// View factories keyed by ModelKindDefinition.viewClass. Kinds without an
        /// entry fall back to DefaultModelView. Override to wire custom views.
        /// </summary>
        protected virtual Dictionary<string, Func<GameObject, Views.ModelViewBase>> CreateViewFactories() => new();

        public void Install(ContainerBuilder builder)
        {
            builder.AddSingleton(container =>
            {
                var eventBus = container.Resolve<IEventBus>();
                var factory = container.Resolve<IGameObjectFactory>();

                var resolver = new PrimeTweenAnimationResolver();
                foreach (var profile in CreateEffectProfiles())
                    resolver.RegisterProfile(profile);

                var database = ModelCatalogDatabase.LoadFromResources();
                var service = new ModelCatalogService(eventBus, factory, resolver, database, CreateViewFactories());
                resolver.InstanceResolver = service.ResolveInstanceForEffects;

                return (IModelCatalogService)service;
            }, typeof(IModelCatalogService));
        }

        public ISystemTestFactory CreateTestFactory() => new ModelCatalogTestFactory(CreateViewFactories());
    }
}
